- type: entity
  id: BasePart
  parent: BaseItem
  name: body part
  abstract: true
  components:
  - type: BodyPart
  - type: StaticPrice
    price: 100
  - type: Tag
    tags:
    - Trash

- type: entity
  id: BaseChest
  name: chest
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Chest

- type: entity
  id: BaseGroin
  name: groin
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Groin

- type: entity
  id: BaseHead
  name: head
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Head
  - type: Input
    context: ghost
  - type: Tag
    tags:
    - Head

- type: entity
  id: BaseLeftArm
  name: left arm
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: LeftArm

- type: entity
  id: BaseRightArm
  name: right arm
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: RightArm

- type: entity
  id: BaseLeftHand
  name: left hand
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: LeftHand

- type: entity
  id: BaseRightHand
  name: right hand
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: RightHand

- type: entity
  id: BaseLeftLeg
  name: left leg
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: LeftLeg
  - type: MovementBodyPart

- type: entity
  id: BaseRightLeg
  name: right leg
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: RightLeg
  - type: MovementBodyPart

- type: entity
  id: BaseLeftFoot
  name: left foot
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: LeftFoot

- type: entity
  id: BaseRightFoot
  name: right foot
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: RightFoot
